apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "veleroNotification.fullname" . }}
  labels:
    {{- include "veleroNotification.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "veleroNotification.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "veleroNotification.serviceAccountName" . }}
